title: "CloudSim Plus" 
description: "A modern, full-featured, highly extensible and easier-to-use Java 8+ Framework for Modeling and Simulation of Cloud Computing Infrastructures and Services" 
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect
encoding: utf-8
  
exclude:
  - CONTRIBUTING.md
  - .github
  - .gitignore

plugins:
  - jekyll-mentions
  - jemoji

webrick:
  headers:
    keywords: "CloudSim Plus,CloudSim,Cloud Computing,Simulation,Framework,IaaS,PaaS,SaaS,Java 8,Maven,Maven Central"
