title: "CloudSim Plus" 
description: "State-of-the-art Framework ğŸ— for Cloud Computing â›…ï¸ Simulation: a modern, full-featured, easier-to-use, highly extensible ğŸ§©, faster ğŸš€ and more accurate â˜•ï¸ Java 17+ tool for cloud computing research ğŸ“" 
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect
encoding: utf-8
  
exclude:
  - CONTRIBUTING.md
  - .github
  - .gitignore

plugins:
  - jekyll-mentions
  - jemoji

webrick:
  headers:
    keywords: "CloudSim Plus,CloudSim,Cloud Computing,Simulation,Framework,IaaS,PaaS,SaaS,Java,Maven,Maven Central"
